[Cutoff]
Auto Optimisation=1
Climb cut=0
CodeSnip=-1
Comment=
cutBias=0.5
Depth=0
Edge overlap=5
Enabled=0
Feed Rate=1
Finish allowance=0
Function=15
Grid size=50
Ignore rules=0
LayerName=
Lead in=-1
Lead in type=0
Lead out=-1
Lead out type=0
Leadins on open paths=0
Maximum X size=2000
Maximum Y size=2000
Minimum X size=500
Minimum Y size=500
NameString=
offsetOpen=0
Plunge Rate=100
Rectangular=0
Reverse open paths=0
Start depth=0
Start point=0
tabWidth=1
Tool=1
[Misc]
Count=1
FileVersion=3
optBias=0.46
Optimisation=0
Template=0
[OpOrder]
[Part 0]
Angle=-1.570796326794897
copyOf=-1
DrawingFile=C:\Dokumente und Einstellungen\Steuerer\Desktop\Fifi_Bauteiltester_Front\Frontplatte_Rueck.dxf
enabled=1
HRef=0
Locked=0
name=Frontplatte_Rueck
VRef=0
XPos=-23
YPos=38.250000000000007
[Part 0Process0]
AngleThreshold=0.5
Auto Optimisation=1
Climb cut=1
CodeSnip=-1
Comment=Zweischneider
Coolant=1
cutBias=0.5
Depth=2
Enabled=0
Feed Rate=80
Finish allowance=-0.1
Function=0
Ignore rules=2
Increment=2
LayerName=Taster
Lead in=3
Lead in type=1
Lead out=3
Lead out type=1
Leadins on open paths=0
NameString=Inside Offset, Taster, T54: Mill/router, 3 mm diameter, 2 mm Deep
offsetOpen=1
Overcut=0
Plunge Rate=20
Ramp angle=0
Reverse open paths=1
Spindle speed=10000
Start depth=0
Start point=2
TabCleanup=1
TabDepth=2
tabWidth=20
Tool=54
[Part 0Process1]
AngleThreshold=0.5
Auto Optimisation=1
Climb cut=1
CodeSnip=-1
Comment=Zweischneider
Coolant=1
cutBias=0.5
Depth=0.6
Enabled=0
Feed Rate=80
Finish allowance=-0.1
Function=0
Ignore rules=2
Increment=2
LayerName=Kontakt_Absatz
Lead in=3
Lead in type=1
Lead out=3
Lead out type=1
Leadins on open paths=0
NameString=Inside Offset, Kontakt_Absatz, T54: Mill/router, 3 mm diameter, 0.6 mm Deep
offsetOpen=1
Overcut=0
Plunge Rate=20
Ramp angle=0
Reverse open paths=1
Spindle speed=10000
Start depth=0
Start point=2
TabCleanup=1
TabDepth=2
tabWidth=20
Tool=54
[Part 0Process2]
AngleThreshold=0.5
Auto Optimisation=1
Climb cut=1
CodeSnip=-1
Comment=Zweischneider
Coolant=1
cutBias=0.5
Depth=2
Enabled=0
Feed Rate=80
Finish allowance=-0.1
Function=0
Ignore rules=2
Increment=2
LayerName=Kontakt_durch
Lead in=3
Lead in type=1
Lead out=3
Lead out type=1
Leadins on open paths=0
NameString=Inside Offset, Kontakt_durch, T54: Mill/router, 3 mm diameter, 2 mm Deep
offsetOpen=1
Overcut=0
Plunge Rate=20
Ramp angle=0
Reverse open paths=1
Spindle speed=10000
Start depth=0
Start point=2
TabCleanup=1
TabDepth=2
tabWidth=20
Tool=54
[Part 0Process3]
AngleThreshold=0.5
Auto Optimisation=1
Climb cut=1
CodeSnip=-1
Comment=Zweischneider
Coolant=1
cutBias=0.5
Depth=2
Enabled=0
Feed Rate=80
Finish allowance=0
Function=0
Ignore rules=2
Increment=2
LayerName=LCD_durch
Lead in=3
Lead in type=1
Lead out=3
Lead out type=1
Leadins on open paths=0
NameString=Inside Offset, LCD_durch, T54: Mill/router, 3 mm diameter, 2 mm Deep
offsetOpen=1
Overcut=0
Plunge Rate=20
Ramp angle=0
Reverse open paths=1
Spindle speed=10000
Start depth=0
Start point=2
TabCleanup=1
TabDepth=2
tabWidth=20
Tool=54
[Part 0Process4]
AngleThreshold=0.5
Auto Optimisation=1
Climb cut=1
CodeSnip=-1
Comment=Zweischneider
Coolant=1
cutBias=0.5
Depth=0.6
Enabled=0
Feed Rate=80
Finish allowance=0
Function=0
Ignore rules=2
Increment=2
LayerName=LCD_Absatz
Lead in=3
Lead in type=1
Lead out=3
Lead out type=1
Leadins on open paths=0
NameString=Inside Offset, LCD_Absatz, T54: Mill/router, 3 mm diameter, 0.6 mm Deep
offsetOpen=1
Overcut=1
Plunge Rate=20
Ramp angle=0
Reverse open paths=1
Spindle speed=10000
Start depth=0
Start point=2
TabCleanup=1
TabDepth=2
tabWidth=20
Tool=54
[Part 0Process5]
AngleThreshold=0.5
Auto Optimisation=1
Climb cut=1
CodeSnip=-1
Comment=Zweischneider
Coolant=1
cutBias=0.5
Depth=0.6
Enabled=1
Feed Rate=80
Finish allowance=0
Function=2
Ignore rules=2
Increment=2
LayerName=LCD_durch
Lead in=3
Lead in type=1
Lead out=3
Lead out type=1
Leadins on open paths=0
NameString=No Offset, LCD_durch, T54: Mill/router, 3 mm diameter, 0.6 mm Deep
offsetOpen=1
Overcut=1
Plunge Rate=20
Ramp angle=0
Reverse open paths=1
Spindle speed=10000
Start depth=0
Start point=2
TabCleanup=1
TabDepth=2
tabWidth=20
Tool=54
[Table]
MaxHeight=1000
Origin=4
RapidSpeed=2000
tableOrigin=4
TableX1=-230
TableX2=230
TableY1=-90
TableY2=90
ToolTime=0
X1=-140
X2=140
Y1=-70
Y2=70
[Tool0]
Angle=2.05949
Comment=
Diameter=10
Feed rate=100
Flute length=20
NameString=Mill/router, 10 mm diameter
Number=10
Offset=0
Plunge Rate=20
Ramp angle=0.174533
Spindle direction=0
Spindle speed=1000
Type=0
Z Increment=10
[Tool1]
Angle=0.5
Comment=
Diameter=12
Feed rate=200
Flute length=20
NameString=Mill/router, 12 mm diameter
Number=12
Offset=0
Plunge Rate=10
Ramp angle=0.174533
Spindle direction=0
Spindle speed=12000
Type=0
Z Increment=6
[Tool10]
Angle=0.5
Comment=
Diameter=0.9
Flute length=10
NameString=Drill, 0.9 mm diameter
Number=103
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool11]
Angle=0.5
Comment=
Diameter=1.1
Flute length=10
NameString=Drill, 1.1 mm diameter
Number=104
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool12]
Angle=0.5
Comment=
Diameter=1.5
Flute length=10
NameString=Drill, 1.5 mm diameter
Number=105
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool13]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=1.7
Flute length=10
NameString=Drill, 1.7 mm diameter
Number=106
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool14]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=2
Flute length=10
NameString=Drill, 2 mm diameter
Number=107
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool15]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=2.8
Flute length=10
NameString=Drill, 2.8 mm diameter
Number=108
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool16]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=1
Flute length=10
NameString=Drill, 1 mm diameter
Number=121
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=2
[Tool17]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=1.5
Flute length=17
NameString=Drill, 1.5 mm diameter
Number=122
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=3
[Tool18]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=2
Flute length=23
NameString=Drill, 2 mm diameter
Number=123
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=4
[Tool19]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=2.5
Flute length=29
NameString=Drill, 2.5 mm diameter
Number=124
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool2]
Angle=2.05949
Comment=
Diameter=4
Feed rate=200
Flute length=10
NameString=Mill/router, 4 mm diameter
Number=50
Offset=0
Plunge Rate=50
Ramp angle=0
Spindle direction=0
Spindle speed=5000
Type=0
Z Increment=2
[Tool20]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=3
Flute length=34
NameString=Drill, 3 mm diameter
Number=125
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=6
[Tool21]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=3.2
Flute length=34
NameString=Drill, 3.2 mm diameter
Number=126
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=6
[Tool22]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=3.5
Flute length=38
NameString=Drill, 3.5 mm diameter
Number=127
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=7
[Tool23]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=4
Flute length=40
NameString=Drill, 4 mm diameter
Number=128
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=8
[Tool24]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=4.5
Flute length=45
NameString=Drill, 4.5 mm diameter
Number=129
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=2000
Type=1
Z Increment=9
[Tool25]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=4.8
Flute length=52
NameString=Drill, 4.8 mm diameter
Number=130
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=2000
Type=1
Z Increment=9.6
[Tool26]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=5
Flute length=54
NameString=Drill, 5 mm diameter
Number=131
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=2000
Type=1
Z Increment=10
[Tool27]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=5.5
Flute length=55
NameString=Drill, 5.5 mm diameter
Number=132
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=2000
Type=1
Z Increment=11
[Tool28]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=6
Flute length=55
NameString=Drill, 6 mm diameter
Number=133
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1500
Type=1
Z Increment=10
[Tool29]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=6.5
Flute length=63
NameString=Drill, 6.5 mm diameter
Number=134
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1500
Type=1
Z Increment=10
[Tool3]
Angle=2.05949
Comment=
Diameter=5
Feed rate=200
Flute length=9
NameString=Mill/router, 5 mm diameter
Number=51
Offset=0
Plunge Rate=50
Ramp angle=0
Spindle direction=0
Spindle speed=5000
Type=0
Z Increment=2.5
[Tool30]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=7
Flute length=65
NameString=Drill, 7 mm diameter
Number=135
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1500
Type=1
Z Increment=10
[Tool31]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=7.5
Flute length=65
NameString=Drill, 7.5 mm diameter
Number=136
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1500
Type=1
Z Increment=10
[Tool32]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=8
Flute length=68
NameString=Drill, 8 mm diameter
Number=137
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1000
Type=1
Z Increment=10
[Tool33]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=8.5
Flute length=69
NameString=Drill, 8.5 mm diameter
Number=138
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1000
Type=1
Z Increment=10
[Tool34]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=9
Flute length=73
NameString=Drill, 9 mm diameter
Number=139
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1000
Type=1
Z Increment=10
[Tool35]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=9.5
Flute length=71
NameString=Drill, 9.5 mm diameter
Number=140
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1000
Type=1
Z Increment=10
[Tool36]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=10
Flute length=81
NameString=Drill, 10 mm diameter
Number=141
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=1000
Type=1
Z Increment=10
[Tool37]
Angle=0.349066
Comment=
Diameter=0.1
Feed rate=300
Flute length=10
NameString=V cutter, 0.1 mm diameter
Number=201
Offset=0
Plunge Rate=100
Ramp angle=0.01
Spindle direction=0
Spindle speed=20000
Type=2
Z Increment=0.1
[Tool38]
Angle=0.2
Comment=
Diameter=2
Feed rate=200
Flute length=4
NameString=V cutter, 2 mm diameter
Number=202
Offset=0
Plunge Rate=50
Ramp angle=0
Spindle direction=0
Spindle speed=5000
Type=2
Z Increment=2
[Tool4]
Angle=0.5
Comment=
Diameter=6
Feed rate=200
Flute length=9
NameString=Mill/router, 6 mm diameter
Number=52
Offset=0
Plunge Rate=50
Ramp angle=0.349066
Spindle direction=0
Spindle speed=2000
Type=0
Z Increment=3
[Tool5]
Angle=0.5
Comment=
Diameter=1.6
Feed rate=200
Flute length=10
NameString=Mill/router, 1.6 mm diameter
Number=53
Offset=0
Plunge Rate=10
Ramp angle=0
Spindle direction=0
Spindle speed=10000
Type=0
Z Increment=0.8
[Tool6]
Angle=0.5
Comment=
Diameter=3
Feed rate=200
Flute length=55
NameString=Mill/router, 3 mm diameter
Number=54
Offset=0
Plunge Rate=100
Ramp angle=0
Spindle direction=0
Spindle speed=10000
Type=0
Z Increment=0.8
[Tool7]
Angle=0.5
Comment=
Diameter=8
Feed rate=200
Flute length=21
NameString=Mill/router, 8 mm diameter
Number=56
Offset=0
Plunge Rate=100
Ramp angle=0
Spindle direction=0
Spindle speed=10000
Type=0
Z Increment=1
[Tool8]
Angle=0.5
Comment=VHM-Bohrer, Bungard
Diameter=0.6
Flute length=10
NameString=Drill, 0.6 mm diameter
Number=101
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[Tool9]
Angle=0.5
Comment=
Diameter=0.8
Flute length=10
NameString=Drill, 0.8 mm diameter
Number=102
Offset=0
Plunge Rate=10
Spindle direction=0
Spindle speed=12000
Type=1
Z Increment=5
[ToolChange]
BeforeCode=
Code=
noSafeZ=0
UseX=0
UseY=0
UseZ=0
X=0
Y=0
Z=0
[Work]
Bottom=10
Clearance=11
isPolygon=0
Notes=
Origin=6
ParkX=0
ParkY=0
ParkZ=30
PlungeSafety=0.5
polyLayer=
polyPart=0
Thickness=1.6
UseX=0
UseY=0
UseZ=1
X1=0
X2=275
Y1=0
Y2=100
[BinaryDataStart]%         C@     ─1@   Leiterplatte              ЮD@     ─1ю         Cю     ─1ю         Cю      7ю  -DTШ!Ы©	          
        @                  Cю     ─1ю         Cю     ─:@         Cю      7ю          	          
        @                  Cю     ─:@        ЮD@     ─:@         Cю      7ю  -DTШ!Ы?	          
        @                 ЮD@     ─:@        ЮD@     ─1ю         Cю      7ю  -DTШ!	@	          
        @          Taster         fffffФ3@      ю   лллллL,@     ─&ю   лллллL,@      ю  -DTШ!Ы?	  -DTШ!Ы?
        @            лллллL,@     ─&ю   лллллл @     ю   лллллL,@      ю  -DTШ!Ы?	  -DTШ!	@
        @            лллллл @     ю   лллллL,@      п?   лллллL,@      ю  -DTШ!Ы?	  -DTШ!Ы©
        @            лллллL,@      п?   fffffФ3@      ю   лллллL,@      ю  -DTШ!Ы?	          
        @          Kontakt_Absatz               юz╝GАzю   fffffФ$ю╓p=
вё)ю   fffffФ$юz╝GАzю  -DTШ!Ы?	  -DTШ!Ы?
  нллллл@            fffffФ$ю╓p=
вё)ю   fffffФ1ю|╝GАzю   fffffФ$юz╝GАzю  -DTШ!Ы?	  -DTШ!	@
  нллллл@            fffffФ1ю|╝GАzю   fffffФ$ю╗p=
вё @   dffffФ$ю|╝GАzю  -DTШ!Ы?	  -DTШ!Ы©
  пллллл@            fffffФ$ю╗p=
вё @         юz╝GАzю   fffffФ$юz╝GАzю  -DTШ!Ы?	          
  нллллл@          Kontakt_durch         ░≥≥≥≥≥юz╝GАzю   fffffФ$ю>
вёp╫(ю   fffffФ$юz╝GАzю  -DTШ!Ы?	  -DTШ!Ы?
       @            fffffФ$ю>
вёp╫(ю   43333s1ю|╝GАzю   fffffФ$юz╝GАzю  -DTШ!Ы?	  -DTШ!	@
       @            43333s1ю|╝GАzю   fffffФ$ю ╝GАzЗ?   fffffФ$юz╝GАzю  -DTШ!Ы?	  -DTШ!Ы©
       @            fffffФ$ю ╝GАzЗ?   ░≥≥≥≥≥юz╝GАzю   fffffФ$юz╝GАzю  -DTШ!Ы?	          
       @          LCD_Absatz              ЮB@      @        @=ю      @   fffffФ$юz╝GАzю  -DTШ!Ы©	          
       @                 @=ю      @        @=юлллллл8@   fffffФ$юz╝GАzю          	          
       @                 @=юлллллл8@        ЮB@лллллл8@   fffffФ$юz╝GАzю  -DTШ!Ы?	          
       @                 ЮB@лллллл8@        ЮB@      @   fffffФ$юz╝GАzю  -DTШ!	@	          
       @         
 LCD_durch               A@≤≥≥≥≥≥@        ю9ю≤≥≥≥≥≥@   fffffФ$юz╝GАzю  -DTШ!Ы©	          
       @                 ю9ю≤≥≥≥≥≥@        ю9юffffff6@   fffffФ$юz╝GАzю          	          
       @                 ю9юffffff6@         A@ffffff6@   fffffФ$юz╝GАzю  -DTШ!Ы?	          
       @                  A@ffffff6@         A@≤≥≥≥≥≥@   fffffФ$юz╝GАzю  -DTШ!	@	          
       @          Symbole              ЮAю      7ю         Cю     ─4ю         Cю      7ю  -DTШ!Ы©	  -DTШ!Ы?
        @                  Cю     ─4ю        `Dю      7ю         Cю      7ю  -DTШ!Ы©	          
        @                 `Dю      7ю         Cю     ─9ю         Cю      7ю  -DTШ!Ы©	  -DTШ!Ы©
        @                  Cю     ─9ю        ЮAю      7ю         Cю      7ю  -DTШ!Ы©	  -DTШ!	@
        @          Symbole              ╟Aю      7ю         Cю     Ю9ю         Cю      7ю  -DTШ!Ы?	  -DTШ!Ы?
        @                  Cю     Ю9ю        ░Dю      7ю         Cю      7ю  -DTШ!Ы?	  -DTШ!	@
        @                 ░Dю      7ю         Cю      4ю         Cю      7ю  -DTШ!Ы?	  -DTШ!Ы©
       @                  Cю      4ю        ╟Aю      7ю         Cю      7ю  -DTШ!Ы?	          
        @          Symbole              ЮDю      7ю        `Aю      7ю         Cю      7ю  -DTШ!Ы?	          
        @          Symbole               Cю     ─:ю         Cю     ─3ю         Cю      7ю          	          
        @                 @         @               ЪЪЪЪ     fffffФ3@        ю       #    $                          @         @               ЪЪЪЪ     ЭЪЪЪЪЪю  y╝GАzю       #    $                        @         @               ЪЪЪЪ     ■≥≥≥≥≥ю  z╝GАzю       #    $                        @         @               ЪЪЪЪ           A@  ≤≥≥≥≥≥@       #    $                        @         @               ЪЪЪЪ          ЮB@        @       #    $                        @         @               ЪЪЪЪ           A@  ≤≥≥≥≥≥@       #    $                   